### ISSUE TITLE
QC - Home

### ISSUE THREAD

**Issue by muhammad-suleman-com** [ComputanTeam/enticedge-beyondbooksmart#28]
```[tasklist]
### Tasks
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/2
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/3
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/4
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/24
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/25
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/26
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/27
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/29
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/30
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/31
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/32
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/33
```

**Comment by muhammad-suleman-com** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/23
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/27
```

**Comment by muhammad-suleman-com** [comment]
Kindly review the URL to the stage page on the homepage. Please follow the instructions mentioned above for details.

Page URL:-
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Comment by awais-abbas-com** [comment]
Task has been completed.
